### ISSUE TITLE
Problem with emit method

### ISSUE THREAD

**Issue by chiccomotta** [PacktPublishing/Angular-Projects#12]
Hi, I have a problem with the code in flash.component.ts in chapter 2 (ng-flashcard project):

```
  markCorrect() {
    this.onRememberedChange.emit({
      id: this.flash.id.toString(),
      flag: 'correct'
    })
  }
```

I receive this error :  error TS2345: Argument of type '{ id: string; flag: string; }' is not assignable to parameter of type 'string'.

I think the method emit accepts obly strings not object. Please help me thanks.

**Comment by chiccomotta** [comment]
Solved! thanks anyway

**Comment by mohammedzamakhan** [comment]
Great @chiccomotta
